#define one Q
#define two W
#define three E
#define four R
#define five T
#define six Y
#define seven U
#define eight I
#define nine O
#define ten P
#define eleven A
#define twelve S
#define thirteen D
#define fourteen F
#define fifteen G
#define sixteen H
#define seventeen J
#define eighteen K
#define nineteen L
